version: "3"
services:
  ubuntu:
    # image: ubuntu
    # 適宜変えること
    container_name: "tenno-hai-ssh"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    # 適宜変えること
    command: /sbin/init
    privileged: true
    # 適宜変えること
    ports:
      - "127.0.0.1:22222:22"
    volumes:
      - "./ubuntu/etc/ssh:/etc/ssh"
      - "./tmp/test.py:/tmp/test.py"